[project]
# The site_name is shown in the page header and the browser window title: https://zensical.org/docs/setup/basics/#site_name
site_name = "LAAC-LSCP Documentation"

# The site_description is included in the HTML head and should contain a
# meaningful description of the site content for use by search engines: https://zensical.org/docs/setup/basics/#site_description
site_description = "The documentation for the tools developed at the LAAC-LSCP."

# The site_author attribute. This is used in the HTML head element: https://zensical.org/docs/setup/basics/#site_author
site_author = "Tarek Kunze"

# Read more: https://zensical.org/docs/setup/basics/#site_url
#site_url = "https://www.example.com/"

# Read more: https://zensical.org/docs/setup/basics/#copyright
copyright = """
Copyright &copy; 2026 The authors
"""


# Read more: https://zensical.org/docs/setup/navigation/
nav = [
    { "Get started" = "index.md" },
    { "VTC 2.0" = [
        "vtc2/usage.md",
        "vtc2/selecting-tresholds.md",
    ]},
]


# Read more: https://zensical.org/docs/customization/#additional-css
#extra_css = ["stylesheets/extra.css"]

# Read more: https://zensical.org/docs/customization/#additional-javascript
#extra_javascript = ["javascripts/extra.js"]

# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------
[project.theme]
#variant = "classic"

# https://zensical.org/docs/customization/#extending-the-theme
#custom_dir = "overrides"

# Read more:
# - https://zensical.org/docs/setup/logo-and-icons/#favicon
# - https://developer.mozilla.org/en-US/docs/Glossary/Favicon
#favicon = "images/favicon.png"

# https://zensical.org/docs/setup/language/
language = "en"

features = [
    # https://zensical.org/docs/authoring/code-blocks/#code-annotations
    "content.code.annotate",

    # https://zensical.org/docs/authoring/code-blocks/#code-copy-button
    "content.code.copy",

    # https://zensical.org/docs/authoring/code-blocks/#code-selection-button
    "content.code.select",

    # https://zensical.org/docs/authoring/footnotes/#footnote-tooltips
    "content.footnote.tooltips",

    # https://zensical.org/docs/authoring/tooltips/#improved-tooltips
    "content.tooltips",

    # https://zensical.org/docs/setup/footer/#navigation
    "navigation.footer",

    # https://zensical.org/docs/setup/navigation/#section-index-pages
    "navigation.indexes",

    # https://zensical.org/docs/setup/navigation/#instant-navigation
    "navigation.instant",

    # https://zensical.org/docs/setup/navigation/#instant-prefetching
    "navigation.instant.prefetch",

    # https://zensical.org/docs/setup/navigation/#navigation-path
    "navigation.path",

    # When sections are enabled, top-level sections are rendered as groups in
    # the sidebar for viewports above 1220px, but remain as-is on mobile.
    # https://zensical.org/docs/setup/navigation/#navigation-sections
    "navigation.sections",

    # https://zensical.org/docs/setup/navigation/#back-to-top-button
    "navigation.top",

    # https://zensical.org/docs/setup/navigation/#anchor-tracking
    "navigation.tracking",

    # https://zensical.org/docs/setup/search/#search-highlighting
    "search.highlight",
]

# ----------------------------------------------------------------------------
# https://zensical.org/docs/setup/colors/
[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"



# ----------------------------------------------------------------------------
# - https://zensical.org/docs/setup/logo-and-icons
# - https://zensical.org/docs/authoring/icons-emojis/#search
[project.theme.icon]
logo = "lucide/book-text"

# ----------------------------------------------------------------------------
# The "extra" section contains miscellaneous settings.
#[[project.extra.social]]
